package pack_bd;
// Generated 25 mars 2022, 16:47:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "bd_locationvehicule")
public class Admin implements java.io.Serializable {

	private Integer idAdmin;
	private String nom;
	private String prenom;
	private String mdpAdmin;
	private int numTel;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Admin() {
	}

	public Admin(String nom, String prenom, String mdpAdmin, int numTel) {
		this.nom = nom;
		this.prenom = prenom;
		this.mdpAdmin = mdpAdmin;
		this.numTel = numTel;
	}

	public Admin(String nom, String prenom, String mdpAdmin, int numTel, Set<Reservation> reservations) {
		this.nom = nom;
		this.prenom = prenom;
		this.mdpAdmin = mdpAdmin;
		this.numTel = numTel;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_admin", unique = true, nullable = false)
	public Integer getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(Integer idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "mdp_admin", nullable = false, length = 15)
	public String getMdpAdmin() {
		return this.mdpAdmin;
	}

	public void setMdpAdmin(String mdpAdmin) {
		this.mdpAdmin = mdpAdmin;
	}

	@Column(name = "num_Tel", nullable = false)
	public int getNumTel() {
		return this.numTel;
	}

	public void setNumTel(int numTel) {
		this.numTel = numTel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
