package pack_bd;
// Generated 25 mars 2022, 16:47:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "bd_locationvehicule")
public class Client implements java.io.Serializable {

	private Integer NClient;
	private String nom;
	private String prenom;
	private String NCni;
	private int numTel;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Client() {
	}

	public Client(String nom, String prenom, String NCni, int numTel) {
		this.nom = nom;
		this.prenom = prenom;
		this.NCni = NCni;
		this.numTel = numTel;
	}

	public Client(String nom, String prenom, String NCni, int numTel, Set<Reservation> reservations) {
		this.nom = nom;
		this.prenom = prenom;
		this.NCni = NCni;
		this.numTel = numTel;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "n_client", unique = true, nullable = false)
	public Integer getNClient() {
		return this.NClient;
	}

	public void setNClient(Integer NClient) {
		this.NClient = NClient;
	}

	@Column(name = "nom", nullable = false, length = 15)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "n_cni", nullable = false, length = 50)
	public String getNCni() {
		return this.NCni;
	}

	public void setNCni(String NCni) {
		this.NCni = NCni;
	}

	@Column(name = "numTel", nullable = false)
	public int getNumTel() {
		return this.numTel;
	}

	public void setNumTel(int numTel) {
		this.numTel = numTel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
