package pack_bd;
// Generated 25 mars 2022, 16:47:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeVehicule generated by hbm2java
 */
@Entity
@Table(name = "type_vehicule", catalog = "bd_locationvehicule")
public class TypeVehicule implements java.io.Serializable {

	private Integer idType;
	private String nom;
	private float tarifType;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

	public TypeVehicule() {
	}

	public TypeVehicule(String nom, float tarifType) {
		this.nom = nom;
		this.tarifType = tarifType;
	}

	public TypeVehicule(String nom, float tarifType, Set<Vehicule> vehicules) {
		this.nom = nom;
		this.tarifType = tarifType;
		this.vehicules = vehicules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_type", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "nom", nullable = false, length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "tarif_type", nullable = false, precision = 12, scale = 0)
	public float getTarifType() {
		return this.tarifType;
	}

	public void setTarifType(float tarifType) {
		this.tarifType = tarifType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeVehicule")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

}
