package pack_bd;
// Generated 25 mars 2022, 16:47:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name = "vehicule", catalog = "bd_locationvehicule")
public class Vehicule implements java.io.Serializable {

	private Integer NSerie;
	private TypeVehicule typeVehicule;
	private String immat;
	private String serieVehicule;
	private String couleur;
	private String marque;
	private String descripVehicule;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Vehicule() {
	}

	public Vehicule(TypeVehicule typeVehicule, String immat, String serieVehicule, String couleur, String marque,
			String descripVehicule) {
		this.typeVehicule = typeVehicule;
		this.immat = immat;
		this.serieVehicule = serieVehicule;
		this.couleur = couleur;
		this.marque = marque;
		this.descripVehicule = descripVehicule;
	}

	public Vehicule(TypeVehicule typeVehicule, String immat, String serieVehicule, String couleur, String marque,
			String descripVehicule, Set<Reservation> reservations) {
		this.typeVehicule = typeVehicule;
		this.immat = immat;
		this.serieVehicule = serieVehicule;
		this.couleur = couleur;
		this.marque = marque;
		this.descripVehicule = descripVehicule;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "n_serie", unique = true, nullable = false)
	public Integer getNSerie() {
		return this.NSerie;
	}

	public void setNSerie(Integer NSerie) {
		this.NSerie = NSerie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type", nullable = false)
	public TypeVehicule getTypeVehicule() {
		return this.typeVehicule;
	}

	public void setTypeVehicule(TypeVehicule typeVehicule) {
		this.typeVehicule = typeVehicule;
	}

	@Column(name = "immat", nullable = false, length = 50)
	public String getImmat() {
		return this.immat;
	}

	public void setImmat(String immat) {
		this.immat = immat;
	}

	@Column(name = "serie_vehicule", nullable = false, length = 30)
	public String getSerieVehicule() {
		return this.serieVehicule;
	}

	public void setSerieVehicule(String serieVehicule) {
		this.serieVehicule = serieVehicule;
	}

	@Column(name = "couleur", nullable = false, length = 20)
	public String getCouleur() {
		return this.couleur;
	}

	public void setCouleur(String couleur) {
		this.couleur = couleur;
	}

	@Column(name = "marque", nullable = false, length = 20)
	public String getMarque() {
		return this.marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	@Column(name = "descrip_vehicule", nullable = false, length = 100)
	public String getDescripVehicule() {
		return this.descripVehicule;
	}

	public void setDescripVehicule(String descripVehicule) {
		this.descripVehicule = descripVehicule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicule")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
